services:
  - type: web
    name: kristova-vojska-api
    runtime: python
    plan: free
    autoDeploy: false
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn KVZAJEDNICA:app --host 0.0.0.0 --port $PORT
